version: '3.8'

services:
  web:
    build: 
      context: .
      target: web
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://contract:uyfuy^6jji@db:5435/pyramid
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - pyramid-network

  bot:
    build:
      context: .
      target: bot
    environment:
      - DATABASE_URL=postgresql://contract:uyfuy^6jji@db:5435/pyramid
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONPATH=/app
    depends_on:
      - web
      - db
      - redis
    volumes:
      - .:/app
    command: poetry run python -m app.bot.run_bot
    networks:
      - pyramid-network

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=contract
      - POSTGRES_PASSWORD=uyfuy^6jji
      - POSTGRES_DB=pyramid
    ports:
      - "5435:5435"
    command: -p 5435
    networks:
      - pyramid-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pyramid-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pyramid-network

volumes:
  postgres_data:
  redis_data:

networks:
  pyramid-network:
    driver: bridge
